import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  en: {
    'Home': 'Home',
    'Work': 'Work',
    'About Us': 'About Us',
    'Contact': 'Contact',
    'Book A Call': 'Book A Call',
    'Reach Out': 'Reach Out',
    'View Projects': 'View Projects',
    'Privacy Policy': 'Privacy Policy',
    'Terms & Conditions': 'Terms & Conditions',
    'Let\'s Talk': 'Let\'s Talk',
    'Full Name': 'Full Name',
    'Email Address': 'Email Address',
    'Your Budget': 'Your Budget',
    'Project Details': 'Project Details',
    'Submit': 'Submit',
    'Stay updated with our news': 'Stay updated with our news',
    'Transform Your Ideas Today': 'Transform Your Ideas Today',
    'Everything You Need To Thrive Digital': 'Everything You Need To Thrive Digital',
    'Studio': 'Studio',
    'Copyright © XZONE AGENCY': 'Copyright © XZONE AGENCY',
    'Enter your email address': 'Enter your email address',
    'Language': 'AR',
    'Next Project': 'Next Project',
    'Previous Project': 'Previous Project',
    'Send us a message': 'Send us a message',
    'Together can elevate your brand and bring your ideas to life': 'Together can elevate your brand and bring your ideas to life',
    'Contact Information': 'Contact Information',
    'Calls': 'Calls',
    'Chats': 'Chats',
    'Address': 'Address',
    'email': 'email',
    'Phone Number': 'Phone Number',
    'Message': 'Message',
    'Next-Gen Design Agency': 'Next-Gen Design Agency',
    'Next-Gen Design Agency For Growing Brands.': 'Next-Gen Design Agency For Growing Brands.',
    'define': 'define',
    'design': 'design',
    'development': 'development',
    'Branding Mobile & Web App Design for Startups and Giants': 'Branding Mobile & Web App Design for Startups and Giants',
    'who are we': 'who are we',
    'X Zone is a full-service creative and digital marketing agency built for brands that demand attention. From concept to campaign — across print, screen, and every surface in between — we turn vision into visual power.': 'X Zone is a full-service creative and digital marketing agency built for brands that demand attention. From concept to campaign — across print, screen, and every surface in between — we turn vision into visual power.',
    'Expert-Vetted': 'Expert-Vetted',
    'Recognized in the top 1% of freelancers for consistent quality, trust, and expertise.': 'Recognized in the top 1% of freelancers for consistent quality, trust, and expertise.',
    'Clients served': 'Clients served',
    'From startups to giants - each treated like our only one.': 'From startups to giants - each treated like our only one.',
    'Success Score': 'Success Score',
    'All 5-star reviews. No compromises. No "just okay."': 'All 5-star reviews. No compromises. No "just okay."',
    'Years of expertise': 'Years of expertise',
    'Deep experience in UX, branding, and growth-driven design for real-world products.': 'Deep experience in UX, branding, and growth-driven design for real-world products.',
    'Services': 'Services',
    'Our': 'Our',
    'We craft high-impact digital experiences through strategic design, seamless coding, and creative thinking.': 'We craft high-impact digital experiences through strategic design, seamless coding, and creative thinking.',
    'Pricing Plans': 'Pricing Plans',
    'Ready to scale your brand?': 'Ready to scale your brand?',
    'Monthly': 'Monthly',
    'Annually': 'Annually',
    'Focus': 'Focus',
    'Ideal for early-stage visionaries.': 'Ideal for early-stage visionaries.',
    'One active design slot': 'One active design slot',
    '48-hour average delivery': '48-hour average delivery',
    'Direct dashboard collaboration': 'Direct dashboard collaboration',
    'Full source file ownership': 'Full source file ownership',
    'Momentum': 'Momentum',
    'Empire': 'Empire',
    'Custom Pricing': 'Custom Pricing',
    'Got questions? We\'ve got answers': 'Got questions? We\'ve got answers',
    'Everything you need to know about our process, pricing, and how we work together': 'Everything you need to know about our process, pricing, and how we work together',
    'Collaborations': 'Collaborations',
    'Why people love working with us': 'Why people love working with us',
    'We don\'t just finish projects; we build success together. Here is what they think of us': 'We don\'t just finish projects; we build success together. Here is what they think of us',
    'Get Started': 'Get Started',
    'What services does your agency provide?': 'What services does your agency provide?',
    'We specialize in end-to-end digital product creation. This includes UI/UX design, mobile and web app development, brand identity, and strategic growth consulting. We build systems that help category leaders dominate their industries.': 'We specialize in end-to-end digital product creation. This includes UI/UX design, mobile and web app development, brand identity, and strategic growth consulting. We build systems that help category leaders dominate their industries.',
    'How do you approach a new project?': 'How do you approach a new project?',
    'Our process starts with a deep-dive discovery phase to understand your business goals and target audience. We then move into strategic planning, wireframing, high-fidelity design, and finally, robust development and testing.': 'Our process starts with a deep-dive discovery phase to understand your business goals and target audience. We then move into strategic planning, wireframing, high-fidelity design, and finally, robust development and testing.',
    'What is the typical timeline for a project?': 'What is the typical timeline for a project?',
    'Timelines vary based on scope and complexity. A standard branding or UI/UX project typically takes 4-8 weeks, while full-scale web or mobile app development can range from 3-6 months. We provide detailed roadmaps during discovery.': 'Timelines vary based on scope and complexity. A standard branding or UI/UX project typically takes 4-8 weeks, while full-scale web or mobile app development can range from 3-6 months. We provide detailed roadmaps during discovery.',
    'How much do your services cost?': 'How much do your services cost?',
    'We offer flexible pricing models including monthly retainers (starting at $2,350/mo) for ongoing design needs, and custom project-based pricing for larger builds. Every engagement is tailored to deliver maximum ROI.': 'We offer flexible pricing models including monthly retainers (starting at $2,350/mo) for ongoing design needs, and custom project-based pricing for larger builds. Every engagement is tailored to deliver maximum ROI.',
    'About the company': 'About the company',
    'Digital Creative Agency': 'Digital Creative Agency',
    'founded in 2024': 'founded in 2024',

    'Numbers': 'Numbers',
    'Awards we have earned over the years.': 'Awards we have earned over the years.',
    'Awards': 'Awards',
    'Site Of The Day': 'Site Of The Day',
    'Awwwards': 'Awwwards',
    'FWA Of The Day': 'FWA Of The Day',
    'FWA': 'FWA',
    'Website Of The Day': 'Website Of The Day',
    'CSS Design Awards': 'CSS Design Awards',
    'Mobile Excellence': 'Mobile Excellence',
    'Creative Team': 'Creative Team',
    'Passionate professionals from diverse backgrounds': 'Passionate professionals from diverse backgrounds',
    'Description': 'Description',
    'Services Provided': 'Services Provided',
    'our projects': 'our projects',
    'crafting unforgettable experiences': 'crafting unforgettable experiences',
    'Project Type': 'Project Type',
    'Client': 'Client',
    'View Project': 'View Project',
    'No projects found in this category.': 'No projects found in this category.',
    'All': 'All',
    'UI/UX': 'UI/UX',
    'Development': 'Development',
    'Branding': 'Branding',
    'UI/UX Design': 'UI/UX Design',
    'UX/UI Designer': 'UX/UI Designer',
    'We craft high-impact digital experiences through strategic design, seamless coding, and creative thinking.': 'We craft high-impact digital experiences through strategic design, seamless coding, and creative thinking.',
    'Mobile Design': 'Mobile Design',
    'Mobile App Designer': 'Mobile App Designer',
    'Creating intuitive, responsive, and engaging mobile interfaces that users love to interact with every day.': 'Creating intuitive, responsive, and engaging mobile interfaces that users love to interact with every day.',
    'Full-Stack Engineering': 'Full-Stack Engineering',
    'Building robust, scalable, and high-performance applications using cutting-edge modern technologies.': 'Building robust, scalable, and high-performance applications using cutting-edge modern technologies.',
    'Branding Design': 'Branding Design',
    'Brand Strategist': 'Brand Strategist',
    'Developing cohesive visual identities that tell your unique story and resonate deeply with your audience.': 'Developing cohesive visual identities that tell your unique story and resonate deeply with your audience.',
    'Printing Service': 'Printing Service',
    'Print & Packaging': 'Print & Packaging',
    'High-quality print design and merchandising materials that make a tangible impact.': 'High-quality print design and merchandising materials that make a tangible impact.',
    'No image': 'No image',
    'Team members will be displayed here soon.': 'Team members will be displayed here soon.',
    'Contact us': 'Contact us',
    'Alsoug, Portsudan, Sudan': 'Alsoug, Portsudan, Sudan',
    'Project not found': 'Project not found',
  },
  ar: {
    'Home': 'الرئيسية',
    'Work': 'أعمالنا',
    'About Us': 'من نحن',
    'Contact': 'أتصل بنا',
    'Book A Call': 'احجز مكالمة',
    'Reach Out': 'تواصل معنا',
    'View Projects': 'عرض المشاريع',
    'Privacy Policy': 'سياسة الخصوصية',
    'Terms & Conditions': 'الشروط والأحكام',
    'Let\'s Talk': 'لنتحدث',
    'Full Name': 'الاسم الكامل',
    'Email Address': 'البريد الإلكتروني',
    'Your Budget': 'ميزانيتك',
    'Project Details': 'تفاصيل المشروع',
    'Submit': 'إرسال',
    'Stay updated with our news': 'ابق على اطلاع بأخبارنا',
    'Transform Your Ideas Today': 'حول أفكارك اليوم',
    'Everything You Need To Thrive Digital': 'كل ما تحتاجه للنجاح الرقمي',
    'Studio': 'ستوديو',
    'Copyright © XZONE AGENCY': 'حقوق النشر © وكالة إكس زون',
    'Enter your email address': 'أدخل عنوان بريدك الإلكتروني',
    'Language': 'EN',
    'Next Project': 'المشروع التالي',
    'Previous Project': 'المشروع السابق',
    'Send us a message': 'أرسل لنا رسالة',
    'Together can elevate your brand and bring your ideas to life': 'معاً يمكننا الارتقاء بعلامتك التجارية وتحويل أفكارك إلى واقع',
    'Contact Information': 'معلومات الاتصال',
    'Calls': 'المكالمات',
    'Chats': 'المحادثات',
    'Address': 'العنوان',
    'email': 'البريد الإلكتروني',
    'Phone Number': 'رقم الهاتف',
    'Message': 'الرسالة',
    'Next-Gen Design Agency': 'وكالة تصميم من الجيل القادم',
    'Next-Gen Design Agency For Growing Brands.': 'وكالة تصميم من الجيل القادم للعلامات التجارية النامية.',
    'define': 'تحديد',
    'design': 'تصميم',
    'development': 'تطوير',
    'Branding Mobile & Web App Design for Startups and Giants': 'تصميم العلامات التجارية وتطبيقات الجوال والويب للشركات الناشئة والعملاقة',
    'who are we': 'من نحن',
    'X Zone is a full-service creative and digital marketing agency built for brands that demand attention. From concept to campaign — across print, screen, and every surface in between — we turn vision into visual power.': 'إكس زون هي وكالة خدمات متكاملة للإبداع والتسويق الرقمي، صُممت للعلامات التجارية التي تسعى للتميز ولفت الانتباه. من الفكرة إلى الحملة — عبر المطبوعات والشاشات وكل ما بينهما — نحن نحول الرؤية إلى قوة بصرية.',
    'Expert-Vetted': 'خضع لفحص الخبراء',
    'Recognized in the top 1% of freelancers for consistent quality, trust, and expertise.': 'تم تصنيفنا ضمن أفضل 1% من المستقلين لجودة عملنا الثابتة، والخبرة، والثقة.',
    'Clients served': 'عميل تمت خدمتهم',
    'From startups to giants - each treated like our only one.': 'من الشركات الناشئة إلى العمالقة - يُعامل كل منهم كأنه الوحيد.',
    'Success Score': 'نسبة النجاح',
    'All 5-star reviews. No compromises. No "just okay."': 'جميع التقييمات 5 نجوم. لا تنازلات.',
    'Years of expertise': 'سنة من الخبرة',
    'Deep experience in UX, branding, and growth-driven design for real-world products.': 'خبرة عميقة في تجربة المستخدم، وتصميم العلامات التجارية، والتصميم الموجه للنمو للمنتجات الواقعية.',
    'Services': 'الخدمات',
    'Our': 'خدماتنا',
    'We craft high-impact digital experiences through strategic design, seamless coding, and creative thinking.': 'نحن نصنع تجارب رقمية عالية التأثير من خلال التصميم الاستراتيجي والبرمجة السلسة والتفكير الإبداعي.',
    'Pricing Plans': 'خطط الأسعار',
    'Ready to scale your brand?': 'هل أنت مستعد لتوسيع علامتك التجارية؟',
    'Monthly': 'شهري',
    'Annually': 'سنوي',
    'Focus': 'التركيز',
    'Ideal for early-stage visionaries.': 'مثالي لأصحاب الرؤى في المراحل المبكرة.',
    'One active design slot': 'فتحة تصميم نشطة واحدة',
    '48-hour average delivery': 'متوسط توصيل خلال 48 ساعة',
    'Direct dashboard collaboration': 'تعاون مباشر عبر لوحة القيادة',
    'Full source file ownership': 'ملكية كاملة لملفات المصدر',
    'Momentum': 'الزخم',
    'Empire': 'الإمبراطورية',
    'Custom Pricing': 'تسعير مخصص',
    'Got questions? We\'ve got answers': 'هل لديك أسئلة؟ لدينا إجابات',
    'Everything you need to know about our process, pricing, and how we work together': 'كل ما تحتاج لمعرفته حول عمليتنا وتسعيرها وكيفية العمل معًا',
    'Collaborations': 'التعاون',
    'Why people love working with us': 'لماذا يحب الناس العمل معنا',
    'We don\'t just finish projects; we build success together. Here is what they think of us': 'نحن لا ننهي المشاريع فحسب؛ بل نبني النجاح معًا. إليك ما يعتقدونه عنا',
    'Get Started': 'ابدأ الآن',
    'What services does your agency provide?': 'ما هي الخدمات التي تقدمها وكالتكم؟',
    'We specialize in end-to-end digital product creation. This includes UI/UX design, mobile and web app development, brand identity, and strategic growth consulting. We build systems that help category leaders dominate their industries.': 'نحن متخصصون في إنشاء المنتجات الرقمية من البداية إلى النهاية. يشمل ذلك تصميم واجهة/تجربة المستخدم المستندة إلى الإدراك، وتطوير تطبيقات الجوال والويب، وهوية العلامة التجارية، واستشارات النمو الاستراتيجي. نحن نبني أنظمة تساعد قادة الفئات على السيطرة على صناعاتهم.',
    'How do you approach a new project?': 'كيف تقاربون مشروعاً جديداً؟',
    'Our process starts with a deep-dive discovery phase to understand your business goals and target audience. We then move into strategic planning, wireframing, high-fidelity design, and finally, robust development and testing.': 'تبدأ عمليتنا بمرحلة استكشاف متعمقة لفهم أهداف عملك وجمهورك المستهدف. ثم ننتقل إلى التخطيط الاستراتيجي، ورسم الإطارات الشبكية، والتصميم عالي الدقة، وأخيراً التطوير والاختبار القوي.',
    'What is the typical timeline for a project?': 'ما هو الجدول الزمني النموذجي للمشروع؟',
    'Timelines vary based on scope and complexity. A standard branding or UI/UX project typically takes 4-8 weeks, while full-scale web or mobile app development can range from 3-6 months. We provide detailed roadmaps during discovery.': 'تختلف الجداول الزمنية بناءً على النطاق والتعقيد. يستغرق مشروع هوية العلامة التجارية القياسي أو تصميم UI/UX عادةً من 4 إلى 8 أسابيع، بينما يمكن أن يتراوح تطوير تطبيق ويب أو جوال كامل من 3 إلى 6 أشهر. نقدم خرائط طريق مفصلة خلال مرحلة الاستكشاف.',
    'How much do your services cost?': 'كم تكلف خدماتكم؟',
    'We offer flexible pricing models including monthly retainers (starting at $2,350/mo) for ongoing design needs, and custom project-based pricing for larger builds. Every engagement is tailored to deliver maximum ROI.': 'نقدم نماذج تسعير مرنة تشمل الحفظ الشهري (بدءاً من 2,350 دولار/شهرياً) لاحتياجات التصميم المستمرة، وتسعير مخصص للمشاريع الأكبر. يتم تصميم كل مشاركة لتقديم أقصى عائد على الاستثمار.',
    'About the company': 'عن الشركة',
    'Digital Creative Agency': 'وكالة إبداع رقمي',
    'founded in 2024': 'تأسست في 2024',

    'Numbers': 'الأرقام',
    'Awards we have earned over the years.': 'الجوائز التي حصلنا عليها على مر السنين.',
    'Awards': 'الجوائز',
    'Site Of The Day': 'موقع اليوم',
    'Awwwards': 'أووردز',
    'FWA Of The Day': 'جائزة FWA لليوم',
    'FWA': 'FWA',
    'Website Of The Day': 'موقع اليوم',
    'CSS Design Awards': 'جوائز تصميم CSS',
    'Mobile Excellence': 'التميز على الجوال',
    'Creative Team': 'فريق الإبداع',
    'Passionate professionals from diverse backgrounds': 'محترفون شغوفون بخلفيات متنوعة',
    'Description': 'الوصف',
    'Services Provided': 'الخدمات المقدمة',
    'our projects': 'مشاريعنا',
    'crafting unforgettable experiences': 'صنع تجارب لا تنسى',
    'Project Type': 'نوع المشروع',
    'Client': 'العميل',
    'View Project': 'عرض المشروع',
    'No projects found in this category.': 'لم يتم العثور على مشاريع في هذا القسم.',
    'All': 'الكل',
    'UI/UX': 'تصميم واجهة وتجربة المستخدم',
    'Development': 'تطوير',
    'Branding': 'علامة تجارية',
    'UI/UX Design': 'تصميم واجهة/تجربة المستخدم',
    'UX/UI Designer': 'مصمم واجهة/تجربة مستخدم',
    'We craft high-impact digital experiences through strategic design, seamless coding, and creative thinking.': 'نحن نصنع تجارب رقمية عالية التأثير من خلال التصميم الاستراتيجي والبرمجة السلسة والتفكير الإبداعي.',
    'Mobile Design': 'تصميم تطبيقات الجوال',
    'Mobile App Designer': 'مصمم تطبيقات الجوال',
    'Creating intuitive, responsive, and engaging mobile interfaces that users love to interact with every day.': 'إنشاء واجهات جوال بديهية وسريعة الاستجابة وجذابة يحب المستخدمون التفاعل معها كل يوم.',
    'Full-Stack Engineering': 'هندسة الويب الشاملة (Full-Stack)',
    'Building robust, scalable, and high-performance applications using cutting-edge modern technologies.': 'بناء تطبيقات قوية وقابلة للتطوير وعالية الأداء باستخدام أحدث التقنيات الحديثة.',
    'Branding Design': 'تصميم العلامات التجارية',
    'Brand Strategist': 'استراتيجي العلامات التجارية',
    'Developing cohesive visual identities that tell your unique story and resonate deeply with your audience.': 'تطوير هويات بصرية متماسكة تروي قصتك الفريدة وتتردد صداها بعمق مع جمهورك.',
    'Printing Service': 'خدمات الطباعة',
    'Print & Packaging': 'الطباعة والتغليف',
    'High-quality print design and merchandising materials that make a tangible impact.': 'تصميم مطبوعات ومواد ترويجية عالية الجودة تحدث تأثيراً ملموساً.',
    'No image': 'لا توجد صورة',
    'Team members will be displayed here soon.': 'سيتم عرض أعضاء الفريق هنا قريباً.',
    'Contact us': 'اتصل بنا',
    'Alsoug, Portsudan, Sudan': 'السوق، بورتسودان، السودان',
    'Project not found': 'لم يتم العثور على المشروع',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem('language') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ar' : 'en');
  };

  const t = (key: string) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
